services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v2.3.13
    container_name: 3x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    restart: unless-stopped
    ports:
      - "127.0.0.1:2053:2053"
      - "20000-20010:20000-20010/tcp"
      - "20000-20010:20000-20010/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    security_opt:
      - no-new-privileges:true
