services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v2.3.13
    container_name: 3x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    restart: unless-stopped
    network_mode: host
    privileged: true
