- name: Setup docker compose
  hosts: vps_sw_1
  become: true

  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker
        state: present

    - name: Install docker-compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Add "vpsuser" user to "docker" group
      remote_user: vpsuser
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: true
      tags:
        - docker
