- name: Setup wireguard
  hosts: vps_sw_1
  become: false

  tasks:
    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/wireguard/compose.yml
        dest: ~/Documents/wireguard/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Create docker network
      ansible.builtin.command:
        cmd: docker network create wireguard
      register: out
      changed_when: out.rc == 0
      failed_when: out.rc >= 2

    - name: Deploy wireguard
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: ~/Documents/wireguard/
      register: out
      changed_when: out.rc != 0
