- name: Deploy minio
  hosts: all
  become: false
  vars:
    local_path: "{{ lookup('env', 'PWD') }}/playbooks/minio/"
    remote_install_path: ~/deploy/minio/

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ local_path }}/compose.yaml"
        dest: "{{ remote_install_path }}"
        mode: "0644"
        remote_src: false
    - name: Pull minio
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0

    - name: Deploy minio
      ansible.builtin.command:
        cmd: docker compose up --force-recreate -d
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0
