- name: Deploy ws-logs
  hosts: all
  become: false
  vars:
    local_path: "{{ lookup('env', 'PWD') }}/playbooks/ws-logs/"
    remote_install_path: ~/deploy/ws-logs/
  vars_files:
    - "{{ lookup('env', 'PWD') }}/external_vars.yml"

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ local_path }}/{{ item }}"
        dest: "{{ remote_install_path }}/"
        mode: "0644"
        remote_src: false
      loop:
        - compose.yml
        - .env
        - loki-config.yaml
        - promtail-config.yaml

    - name: Render config templates
      ansible.builtin.template:
        src: "{{ local_path }}/prometheus.yml.j2"
        mode: "0644"
        dest: "{{ remote_install_path }}/prometheus.yml"
        remote_src: false

    - name: Deploy ws-logs
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0
