- name: Deploy ws-logs
  hosts: all
  become: false
  vars:
    remote_install_path: ~/Documents/ws-logs
  vars_files:
    - "{{ lookup('env', 'PWD') }}/external_vars.yml"

  tasks:
    - name: Render config templates
      ansible.builtin.template:
        src: "{{ lookup('env', 'PWD') }}/playbooks/ws-logs/prometheus.yml.j2"
        mode: "0644"
        dest: "{{ remote_install_path }}/prometheus.yml"
        remote_src: false

    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_install_path }}/"
        mode: "0644"
        remote_src: false
      loop:
        - ~/documents/ansible/playbooks/ws-logs/compose.yml
        - ~/documents/ansible/playbooks/ws-logs/.env
        - ~/documents/ansible/playbooks/ws-logs/loki-config.yaml
        - ~/documents/ansible/playbooks/ws-logs/promtail-config.yaml

    - name: Create docker network
      ansible.builtin.command:
        cmd: docker network create ws-logs
      register: out
      changed_when: out.rc == 0
      failed_when: out.rc >= 2

    - name: Deploy ws-logs
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0
