global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "nodeexporter-pi"
    static_configs:
      - targets: ["192.168.1.58:9100"]

  - job_name: "nodeexporter-sw1"
    static_configs:
      - targets: ["77.221.140.146:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "cadvisor-pi"
    static_configs:
      - targets: ["192.168.1.58:3003"]

  - job_name: "cadvisor-sw1"
    static_configs:
      - targets: ["77.221.140.146:3003"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
