sources:
  docker_log_source:
    type: docker_logs
    include_labels:
      - org.opencontainers.group=logging

transforms:
  docker_log_transform:
    type: remap
    inputs:
      - docker_log_source
    source: |-
      .message = parse_json!(.message)
      del(.label)

sinks:
  my_sink_id:
    type: loki
    inputs:
      - docker_log_transform
    endpoint: http://loki:3100
    encoding:
      codec: "json"
    labels:
      service_name: "{{ .container_name }}"
      host: "$VECTOR_LOG_HOST"
      image: "{{ .image }}"
      source: vector
      level: "{{ .message.level }}"
    structured_metadata:
      "*": "{{ .message }}"
