- name: Deploy cadvisor
  hosts: all
  become: false

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/Documents/cadvisor/
        mode: "0644"
        backup: true
        remote_src: false
      loop:
        - "{{ lookup('env', 'PWD') }}/playbooks/cadvisor/compose.yml"

    - name: Deploy cadvisor
      ansible.builtin.command:
        cmd: docker compose up --force-recreate -d
        chdir: ~/Documents/cadvisor
      register: out
      changed_when: out.rc != 0
