services:
  gpu-exporter:
      image: utkuozdemir/nvidia_gpu_exporter:1.3.0
      container_name: nvidia-gpu-exporter
      restart: unless-stopped
      ports:
        - "9835:9835"
      devices:
        - /dev/nvidiactl:/dev/nvidiactl
        - /dev/nvidia0:/dev/nvidia0
      volumes:
        - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
        - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
        - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
