- name: Deploy dwman-dev
  hosts: vps_sw_1
  become: false

  tasks:
    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/dwman-dev/compose.yaml
        dest: ~/Documents/dwman-dev/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Copy .env file
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/dwman-dev/.env
        dest: ~/Documents/dwman-dev/
        mode: "0644"
        backup: true

    - name: Pull new image dwman-dev
      ansible.builtin.command:
        cmd: docker-compose pull
        chdir: ~/Documents/dwman-dev
      register: out
      changed_when: out.rc != 0

    - name: Deploy dwman-dev
      ansible.builtin.command:
        cmd: docker-compose up --force-recreate -d
        chdir: ~/Documents/dwman-dev
      register: out
      changed_when: out.rc != 0
