- name: Deploy homepage
  hosts: all
  become: false

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: ~/Documents/homepage/{{ item.dest }}
        mode: "0644"
        backup: true
        remote_src: false
      loop:
        - src: ~/documents/ansible/playbooks/homepage/compose.yml
          dest:
        - src: ~/documents/ansible/playbooks/homepage/config/bookmarks.yaml
          dest: config/
        - src: ~/documents/ansible/playbooks/homepage/config/services.yaml
          dest: config/
        - src: ~/documents/ansible/playbooks/homepage/config/settings.yaml
          dest: config
        - src: ~/documents/ansible/playbooks/homepage/config/widgets.yaml
          dest: config/

    - name: Deploy homepage
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: ~/Documents/homepage
      register: out
      changed_when: out.rc != 0
