- name: Deploy homepage
  hosts: all
  become: false
  vars:
    local_path: "{{ lookup('env', 'PWD') }}/playbooks/homepage/"
    remote_install_path: ~/deploy/homepage/
  vars_files:
    - "{{ lookup('env', 'PWD') }}/external_vars.yml"

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ local_path }}/{{ item.src }}"
        dest: "{{ remote_install_path }}/{{ item.dest }}"
        mode: "0644"
        remote_src: false
      loop:
        - src: compose.yml
          dest:
        - src: config/bookmarks.yaml
          dest: config/
        - src: config/settings.yaml
          dest: config
        - src: config/widgets.yaml
          dest: config/

    - name: Render config templates
      ansible.builtin.template:
        src: "{{ local_path }}/config/services.yaml.j2"
        mode: "0644"
        dest: "{{ remote_install_path }}/config/services.yaml"
        remote_src: false

    - name: Deploy homepage
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0
