- name: Restore jellyfin
  hosts: local_workstation
  become: false
  vars:
    backup_dirve: /mnt/storage/backups/ubuntu_ws_01_2024/home

  tasks:
    - name: Restore jellyfin
      ansible.builtin.copy:
        src: /mnt/storage/backups/ubuntu_ws_01_2024/home/Documents/jellyfin
        dest: ~/Documents
        mode: "0755"
        remote_src: true
