services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:12
    container_name: wireguard
    environment:
      - WG_HOST=${WG_HOST}
    volumes:
      - ./wireguard/data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
