- name: Deploy factorio-server
  hosts: all
  become: false
  vars:
    local_path: "{{ lookup('env', 'PWD') }}/playbooks/factorio-server/"
    remote_install_path: ~/deploy/factorio-server/
    backup_name: factorio-server-backup-{{ ansible_date_time.iso8601 }}

  tasks:
    - name: Check map unchanged
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o pipefail
          docker logs factorio-server --since 24h | grep -wc "JOIN"
      register: map_changed
      changed_when: map_changed.stdout | int != 0
      failed_when: map_changed.stdout | int == 0

    - name: Make backup
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          echo "/save {{ backup_name }}.zip" |
          unbuffer -p docker attach factorio-server
        chdir: "{{ remote_install_path }}/data/saves/"
        executable: /bin/bash
      register: out
      changed_when: out.rc != 0

    - name: Wait for backup to finish
      ansible.builtin.wait_for:
        path: "{{ remote_install_path }}/data/saves/{{ backup_name }}.zip"
        state: present
        timeout: 60

    - name: Save backup to cloud
      ansible.builtin.command:
        cmd: |-
          rclone copy ./{{ backup_name }}.zip remote:factorio-bacups
        chdir: "{{ remote_install_path }}/data/saves/"
      register: out
      changed_when: out.rc != 0
