- name: Deploy factorio-server
  hosts: all
  become: false
  vars:
    local_path: "{{ lookup('env', 'PWD') }}/playbooks/factorio-server/"
    remote_install_path: ~/deploy/factorio-server/

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ local_path }}/compose.yaml"
        dest: "{{ remote_install_path }}"
        mode: "0644"
        remote_src: false

    - name: Get current Factorio version
      ansible.builtin.command:
        cmd: >-
          docker inspect factoriotools/factorio:stable
          --format "{{ '{{' }} index .Config.Labels \"factorio.version\" {{ '}}' }}"
      register: factorio_version
      changed_when: factorio_version.rc != 0
      failed_when: factorio_version.rc > 1

    - name: Info
      ansible.builtin.debug:
        msg: "Current Factorio version: {{ factorio_version.stdout | default('unknown', true) }}"

    - name: Pull factorio-server
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0

    - name: Deploy factorio-server
      ansible.builtin.command:
        cmd: docker compose up --force-recreate -d
        chdir: "{{ remote_install_path }}"
      register: out
      changed_when: out.rc != 0

    - name: Get updated Factorio version
      ansible.builtin.command:
        cmd: >-
          docker inspect factoriotools/factorio:stable
          --format "{{ '{{' }} index .Config.Labels \"factorio.version\" {{ '}}' }}"
      register: factorio_version
      changed_when: factorio_version.rc != 0
      failed_when: factorio_version.rc > 1

    - name: Info
      ansible.builtin.debug:
        msg: "Updated Factorio version: {{ factorio_version.stdout | default('unknown', true) }}"
