services:
  caddy:
    image: caddy:2-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
