services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy_data:/data:rw
      - ./caddy_config:/config:rw
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
