services:
  duckdns-ui:
    image: ghcr.io/akorzunin/duckdns-ui:0.1.2
    container_name: duckdns-ui
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./data:/src/data:rw
    restart: unless-stopped
