version: "3.5"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /home/akorz/Documents/transmission/config:/config
      - /mnt/storage/jellyfin_media:/downloads
      - /home/akorz/Documents/transmission/watch:/watch
    ports:
      - 9092:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
