- name: Deploy transmission
  hosts: local_workstation
  become: false

  tasks:
    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/transmission/compose.yaml
        dest: ~/Documents/transmission/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Deploy transmission
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: ~/Documents/transmission
      register: my_output
      changed_when: my_output.rc != 0
