- name: Restore transmission
  hosts: local_workstation
  become: false
  vars:
    backup_dirve: /mnt/storage/backups/ubuntu_ws_01_2024/home/Documents

  tasks:
    - name: Restore transmission
      ansible.builtin.copy:
        src: /mnt/storage/backups/ubuntu_ws_01_2024/home/Documents/transmission
        dest: ~/Documents
        mode: "0755"
        remote_src: true
