- name: Run nvidia test
  hosts: local_workstation
  become: true

  tasks:
    - name: Download the script
      ansible.builtin.get_url:
        url: https://gist.githubusercontent.com/akorzunin/4dfad794fc658502e5c62379191eb4f0/raw/zsh_deb.sh
        dest: /tmp/zsh_deb.sh
        mode: "0755"

# just run  sudo /tmp/zsh_deb.sh on remote :(
    # - name: Run zsh_deb.sh script
    #   ansible.builtin.shell: y | /tmp/zsh_deb.sh
    #   become: true
    #   register: out
    #   changed_when: out.rc != 0

    #   ansible.builtin.shell:
    #     cmd: curl https://gist.githubusercontent.com/akorzunin/4dfad794fc658502e5c62379191eb4f0/raw/zshrc.sh >> ~/.zshrc
    #   become: false
    #   register: out
    #   changed_when: out.rc != 0
    - name: Setup zsh config
      ansible.builtin.get_url:
        url: https://gist.githubusercontent.com/akorzunin/4dfad794fc658502e5c62379191eb4f0/raw/zshrc.sh
        dest: ~/.zshrc
        mode: "0644"
      become: false
      # register: out
      # changed_when: out.rc != 0

    - name: Set zsh as default shell
      ansible.builtin.command: chsh -s /bin/zsh # not works cuz it needs user password anyway
      become: false
      register: out
      changed_when: out.rc != 0
