services:
    open-webui:
        container_name: open-webui
        image: ghcr.io/open-webui/open-webui:v0.5.7
        network_mode: host
        # ports:
        #     - 3033:8080
        # extra_hosts:
        #     - "host.docker.internal:host-gateway"
        volumes:
            - ./data:/app/backend/data
        restart: unless-stopped
