services:
    open-webui:
        container_name: open-webui
        image: ghcr.io/open-webui/open-webui:v0.5.20
        network_mode: host
        volumes:
            - ./data:/app/backend/data
        restart: unless-stopped
