- name: Deploy wol
  hosts: local_pi
  become: false

  tasks:
    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/wake-on-lan/compose.yaml
        dest: ~/Documents/wake-on-lan/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/wake-on-lan/computers.txt
        dest: ~/Documents/wake-on-lan/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Deploy wol
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: ~/Documents/wake-on-lan
      register: my_output
      changed_when: my_output.rc != 0
