- name: Deploy wol
  hosts: local_pi
  become: false

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: ~/Documents/wake-on-lan/
        mode: "0644"
        backup: true
        remote_src: false
      loop:
        - ~/documents/ansible/playbooks/wake-on-lan/compose.yaml
        - ~/documents/ansible/playbooks/wake-on-lan/computers.txt

    - name: Deploy wol
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: ~/Documents/wake-on-lan
      register: out
      changed_when: out.rc != 0
