name: 3proxy
services:
  3proxy:
    image: 3proxy/3proxy:latest
    container_name: 3proxy
    restart: unless-stopped
    ports:
      - 4040:4040
      - 4444:4444
      - "4444:4444/udp"
    volumes:
      - ./proxy-config.cfg:/etc/3proxy/3proxy.cfg:ro
      - ./users.env:/etc/3proxy/users:ro
