- name: Run nvidia test
  hosts: local_workstation
  become: false

  tasks:
    - name: Setup service directory
      ansible.builtin.file:
        path: ~/Documents/nvidia-test
        state: directory
        mode: "0755"

    - name: Copy compose.yaml file to service directory
      ansible.builtin.copy:
        src: ~/documents/ansible/playbooks/nvidia-test/compose.yaml
        dest: ~/Documents/nvidia-test/
        mode: "0644"
        backup: true
        remote_src: false

    - name: Run test container
      ansible.builtin.command:
        chdir: ~/Documents/nvidia-test
        cmd: docker-compose up
      register: docker_compose_output
      changed_when: docker_compose_output.rc != 0

    - name: Debug docker_compose_output as part of a string
      ansible.builtin.debug:
        var: docker_compose_output
