- name: Setup portainer
  hosts: "{{ var_host | default('local_workstation, vps_sw_1') }}"
  become: true

  tasks:
    - name: Create portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:2.20.2
        state: started
        recreate: true
        restart_policy: always
        published_ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
