- name: Setup docker compose
  hosts: local_workstation
  become: true

  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker
        state: present

    - name: Install docker-compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Add "akorz" user to "docker" group
      remote_user: akorz
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: true
      tags:
        - docker
