- name: Install Nvidia drivers
  hosts: local_workstation
  become: true
  tasks:
    - name: Install NVIDIA driver
      ansible.builtin.command:
        cmd: sudo ubuntu-drivers install nvidia:545
      register: istaller_output
      changed_when: istaller_output.rc != 0

    # - name: Add repo
    #   ansible.builtin.shell: |
    #     curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
    #     && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    #     sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    #     sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list


    - name: Install nvidia-container-toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        update_cache: true
        state: present

    - name: Configure docker driver
      ansible.builtin.command:
        cmd: nvidia-ctk runtime configure --runtime=docker
      register: istaller_output
      changed_when: istaller_output.rc != 0

    - name: Restart Docker daemon
      ansible.builtin.service:
        name: docker
        state: restarted
