services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - ./firefly-data/upload:/var/www/html/storage/upload:rw
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    image: "postgres:latest"
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - ./firefly-data/db:/var/lib/postgresql/data:rw
  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: unless-stopped
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '8181:8080'
    depends_on:
      - app
    env_file: .importer.env

networks:
  firefly_iii:
    driver: bridge
