services:
  v2raya:
    image: mzz2017/v2raya:v2.4.9@sha256:47f9acf99b23f19d804ab15303e8a7df7f66913d14c5ce0b39936d036dbb8500
    container_name: v2raya
    restart: unless-stopped
    environment:
      V2RAYA_V2RAY_BIN: /usr/bin/v2raya_core
      V2RAYA_LOG_FILE: /tmp/v2raya.log
    ports:
      - "127.0.0.1:2017:2017"
      - "20171:20171"
    volumes:
      - ./data:/etc/v2raya
    networks:
      - v2raya-proxy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M

networks:
  v2raya-proxy:
    external: true
    name: v2raya-proxy
